export const ADD_ROOM_SESSION_REQUEST = "ADD_ROOM_SESSION_REQUEST";
export const ADD_ROOM_SESSION_SUCCESS = "ADD_ROOM_SESSION_SUCCESS";
export const ADD_ROOM_SESSION_FAILURE = "ADD_ROOM_SESSION_FAILURE";

export const GET_ROOM_SESSION_REQUEST = "GET_ROOM_SESSION_REQUEST";
export const GET_ROOM_SESSION_SUCCESS = "GET_ROOM_SESSION_SUCCESS";
export const GET_ROOM_SESSION_FAILURE = "GET_ROOM_SESSION_FAILURE";

export const UPDATE_ROOM_SESSION_REQUEST = "UPDATE_ROOM_SESSION_REQUEST";
export const UPDATE_ROOM_SESSION_SUCCESS = "UPDATE_ROOM_SESSION_SUCCESS";
export const UPDATE_ROOM_SESSION_FAILURE = "UPDATE_ROOM_SESSION_FAILURE";
