export const ADD_NOT_ALLOCATED_ROOM_REQUEST = "ADD_NOT_ALLOCATED_ROOM_REQUEST";
export const ADD_NOT_ALLOCATED_ROOM_SUCCESS = "ADD_NOT_ALLOCATED_ROOM_SUCCESS";
export const ADD_NOT_ALLOCATED_ROOM_FAILURE = "ADD_NOT_ALLOCATED_ROOM_FAILURE";

export const GET_NOT_ALLOCATED_ROOM_REQUEST = "GET_NOT_ALLOCATED_ROOM_REQUEST";
export const GET_NOT_ALLOCATED_ROOM_SUCCESS = "GET_NOT_ALLOCATED_ROOM_SUCCESS";
export const GET_NOT_ALLOCATED_ROOM_FAILURE = "GET_NOT_ALLOCATED_ROOM_FAILURE";

export const UPDATE_NOT_ALLOCATED_ROOM_REQUEST =
  "UPDATE_NOT_ALLOCATED_ROOM_REQUEST";
export const UPDATE_NOT_ALLOCATED_ROOM_SUCCESS =
  "UPDATE_NOT_ALLOCATED_ROOM_SUCCESS";
export const UPDATE_NOT_ALLOCATED_ROOM_FAILURE =
  "UPDATE_NOT_ALLOCATED_ROOM_FAILURE";
