export const ADD_SESSION_HANDLER_REQUEST = "ADD_SESSION_HANDLER_REQUEST";
export const ADD_SESSION_HANDLER_SUCCESS = "ADD_SESSION_HANDLER_SUCCESS";
export const ADD_SESSION_HANDLER_FAILURE = "ADD_SESSION_HANDLER_FAILURE";

export const GET_SESSION_HANDLER_REQUEST = "GET_SESSION_HANDLER_REQUEST";
export const GET_SESSION_HANDLER_SUCCESS = "GET_SESSION_HANDLER_SUCCESS";
export const GET_SESSION_HANDLER_FAILURE = "GET_SESSION_HANDLER_FAILURE";

export const UPDATE_SESSION_HANDLER_REQUEST = "UPDATE_SESSION_HANDLER_REQUEST";
export const UPDATE_SESSION_HANDLER_SUCCESS = "UPDATE_SESSION_HANDLER_SUCCESS";
export const UPDATE_SESSION_HANDLER_FAILURE = "UPDATE_SESSION_HANDLER_FAILURE";
